routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/oturum/pmenu', 'HomeController@oturum')->name('pmenu')->middleware('auth','onyedi');
    Route::get('/oturum/hesabim', 'HomeController@hesap')->name('hesap')->middleware('auth','onyedi');
Route::get('/anasayfa/hakkimizda', 'HomeController@hk')->name('hk');
Route::get('/anasayfa/kariyerler', 'HomeController@kariyerler')->name('kariyerler');
Route::get('/veosnet/etkinlikler', 'HomeController@etkinlikler')->name('etkinlikler');
Route::get('/veosnet/misyonumuz ve vizyonumuz', 'HomeController@misyon')->name('misyon');
Route::get('/veosnet/iade şartları', 'HomeController@iade')->name('iade');
Route::get('/', 'HomeController@index')->name('home');
Route::get('/contact', 'HomeController@contact')->name('contact');
Route::get('/category/{slug}', 'HomeController@category')->name('category');
Route::get('/product/{slug}', 'HomeController@product')->name('product');
Route::get('/Kurumsal/Bayi Sozlesmesi ve Prosedurler', 'HomeController@bayi')->name('bayi');
Route::get('/Kurumsal/Temsilcilik Sozlesmesi', 'HomeController@temsilcilik')->name('temsilcilik');
Route::get('/Kurumsal/Gizlilik Sozlesmesi','HomeController@gizlilik')->name('gizlilik');
Route::get('/Kurumsal/Dogrudan Satis Sozlesmesi', 'HomeController@dogrudansatis')->name('dogrudansatis');
Route::get('/Kurumsal/Mesafeli Satis Sozlesmesi', 'HomeController@mesafelisatis')->name('mesafelisatis');
Route::get('/Veosnet/İş Modeli', 'HomeController@ismodeli')->name('ismodeli');
Route::get('/Veosnet/Yeni Urunler', 'HomeController@yeniurunler')->name('yeniurunler');
Route::resource('profil-create','ProfilCreateController');
Route::get('dest/{id}','ProfilCreateController@destroy')->name('psil');
Route::get('/Veosnet/Neden Veosnetwork', 'HomeController@nedenveos')->name('nedenveos');
Route::get('/Veosnet/ProfesyonelPazarlama', 'HomeController@ppazarlama')->name('ppazarlama');
Route::get('/PrimMenu/ekip/', 'PrimController@index')->name('ekipagaci')->middleware('auth','onyedi');
Route::get('/VeosNet/cuzdan', 'PrimController@create')->name('cuzdan')->middleware('auth','onyedi');
Route::get('/VeosNet/binary', 'PrimController@binary')->name('binary')->middleware('auth','onyedi');
Route::get('/VeosNet/binary/datatable', 'PrimController@binary_datatable')->name('binary-datatable')->middleware('auth','onyedi');
Route::get('/VeosNet/kazanc', 'PrimController@store')->name('kazanc')->middleware('auth','onyedi');
Route::get('/PrimMenu/{kid}/kazanc', 'PrimController@gonderme')->name('kid')->middleware('auth','onyedi');
Route::get('/view/Kargo', 'HomeController@kargo')->name('kargo');
Route::get('/view/Odemeplanı', 'HomeController@odemeplanı')->name('odemeplanı');
Route::get('/view/basari', 'HomeController@basari')->name('basari');
Route::get('/view/profesyonel_pazarlama', 'HomeController@profesyonelpazarlama')->name('profesyonelpazarlama');
Route::get('/view/genelbakis', 'PrimController@genelbakis')->name('genelbakis')->middleware('auth','onyedi');
Route::get("/view/menu","PrimController@menu")->name('menu')->middleware('auth','onyedi');
Route::get('/view/guvenliodeme','HomeController@cartman')->name('cartman')->middleware('auth','onyedi');
Route::get('/view/TarimOnaylidir','HomeController@tarimbelge')->name('tarimbelge');
Route::get('/view/Kazancozeti','HomeController@kazancozeti')->name('kazancozeti')->middleware('auth','onyedi');
Route::get('/VeosNet/Kazancozeti/datatable','GelirController@kazancozeti_datatable')->name('kazancozeti.datatable')->middleware('auth','onyedi');
Route::get('/VeosNet/gelenpv/datatable','GelenpvController@gelenpv_datatable')->name('gelenpv.datatable')->middleware('auth','onyedi');
Route::get('Veosnet/Pv/Cv Gelirlerim','GelenpvController@index')->name('gelenpvsyf');
Route::get('/VeosNet/gelirlerim','HomeController@gelirlerim')->name('gelirlerim')->middleware('auth','onyedi');
Route::get('VeosNet/S.S.S','HomeController@sss')->name('sss');
Route::resource('mailorder','MailOrderController');
Route::get('Kampanyalar','HomeController@kampanyalar')->name('kampanyalar');
Route::get('haberlerimiz','HomeController@haber2')->name('haberler2');
Route::get('Bilgilendirme','HomeController@bilgilendirme')->name('bilgilendirme21')->middleware('auth','onyedi');
Route::get('hesapbilgileri','HomeController@banka')->name('banka')->middleware('auth','onyedi');
Route::get('VeosNet/Sozlesmeler','HomeController@sozlesmemusteri')->name('sozlesmemusteri');
Route::get('VeosNet/sozlesmelerimiz/{uuid}/download','HomeController@download')->name('sozlesme.download')->middleware('auth');
Route::get('VeosNet/kullaniciilcirosu','HomeController@il_ciro')->name('il_ciro')->middleware('auth','onyedi');
Route::get('VeosNet/kullanicitrciro','HomeController@tr_ciro')->name('tr_ciro')->middleware('auth','onyedi');
Route::get('VeosNet/kullanicidunyaciro','HomeController@dunya_ciro')->name('dunya_ciro')->middleware('auth','onyedi');
Route::get('VeosNet/kullaniciarabaciro','HomeController@araba_ciro')->name('araba_ciro')->middleware('auth','onyedi');
Route::get('VeosNet/kullanicibolgeciro','HomeController@bolge_ciro')->name('bolge_ciro')->middleware('auth','onyedi');
Route::get('veosnet/GuvenliOdeme','HomeController@mailorder')->name('mailorder');
Route::resource('VeosNet/odemetalebi','OdemeTalebiController')->middleware('auth','onyedi');
Route::resource('message','MessageController');
Route::get('/Veosnet/Kataloglar','HomeController@kullanici_katalog')->name('kullanici_katalog');

Route::group(['namespace'=>"Admin"],function (){
    Route::get('/VeosNet/kullanici/katalog/{uuid}/download', 'KatalogController@download')->name('katalog.download');
});
Route::get('VeosNet/EftDurum','HomeController@musteri_eft_durum')->name('musteri_eft_durum')->middleware('auth','onyedi');

Route::get('veosnet/alt-uyelik-ekle','PrimController@farkli_il_kayit_index')->middleware('auth')->name('yeni-alt-bayi');
Route::post('veosnet/alt-uyelik-ekle','PrimController@farkli_il_kayit_store')->middleware('auth')->name('yeni-alt-bayi.store');
Route::get('veosnet/alt-uyeliklerim','PrimController@alt_bayiliklerim')->middleware('auth')->name('alt-bayiliklerim');

Route::get('logout','Auth\LoginController@logout');
    //Route::get('kayit/{konum}','uyelikController@index')->name('kayityapma');
Route::get('kayit/{konum}/{sps}','uyelikController@index')->name('kayityapma')->middleware('auth');
Route::post('kayit','uyelikController@store')->name('kayityapma.kayıt')->middleware('auth');
Route::get('KonumBilgilendirme','PrimController@bilgilendirme')->name('bilgilendirme')->middleware('auth');
Route::get('isteklerim','PrimController@isteklerim')->name('isteklerim')->middleware('auth');
Route::get('ekiptakip','PrimController@ekiptakip')->name('ekiptakip')->middleware('auth');
Route::get('ekiplistesi','PrimController@ekiplistesi')->name('ekiplistesi')->middleware('auth');
Route::get('change-password', 'ChangePasswordController@index')->name('change')->middleware('auth');
Route::post('change-password', 'ChangePasswordController@store')->name('change.password')->middleware('auth');
Route::post('konumlandirin/{ikid}','Admin\TransferController@iskonum')->name('iskonum')->middleware('auth');

Route::post('odeme-cuzdan/{tutar}','GelirController@cuzdanOdeme')->name('cuzdan.odeme')->middleware('auth');
Route::get('bankahesapbilgileri','PrimController@bankahesapbilgileri')->name('bankahesapbilgileri')->middleware('auth');
Route::get('bankahesapbilgileri/{order_no}','PrimController@bankahesapbilgilerikisiyeozel')->name('bankahesapbilgileri.kisiyeozel')->middleware('auth');


Route::group(["middleware" => ["is_thisAdmin","auth"]],function (){
    Route::group(["namespace" => "Admin"], function (){
        Route::resource("admin-users","UsersController");
        Route::get("admin-users/datatable/d","UsersController@users_datatable")->name('admin-users.datatable');
        Route::get("admin-users/datatable/active","UsersController@users_active_datatable")->name('admin-users.active.datatable');
        Route::get("admin-users/datatable/pasive","UsersController@users_passive_datatable")->name('admin-users.passive.datatable');
        Route::resource("admin-category","CategoryController");
        Route::resource("admin-products","ProductController");
        Route::resource("admin-orders","OrderController");
        Route::resource('kariyer','KariyerController');
        Route::resource('transfer','TransferController');
        Route::get('Binarykontrol','TransferController@adminagac')->name('binarykontrol');
        Route::post('admin/admin-pv/{id}/ekle','TransferController@admin_pv_ekleme')->name('admin.pv.ekle');
        Route::post('admin/admin-cv/{id}/ekle','TransferController@admin_cv_ekleme')->name('admin.cv.ekle');
        Route::get('AdminEkiplistesi','TransferController@adminekip')->name('adminekip');
        Route::get('transfer/{id}/sil','TransferController@destroy2')->name('transfersilme');
        Route::post('transfer/{tid}','TransferController@transferet')->name('transfer');
        Route::post('konumlandir/{kdid}','TransferController@konumlandir')->name('konumlandir');
        Route::get('kontrolmenu','TransferController@kontrolmenu')->name('kontrolmenu');
        Route::get('aktif_pasif','TransferController@aktif')->name('aktif');
        Route::get('users-pasif','TransferController@pasif')->name('users.passive');
        Route::get('aracciro','TransferController@araciro')->name('adminaraciro');
        Route::get('tazminat','TransferController@tazminat')->name('tazminat');
        Route::get('tazminat/{id}','TransferController@tazminatode')->name('tazminat-ode');

resources/views/bildirim_url_ornek.blade.php
<?php

	## 2. ADIM için örnek kodlar ##

	## ÖNEMLİ UYARILAR ##
	## 1) Bu sayfaya oturum (SESSION) ile veri taşıyamazsınız. Çünkü bu sayfa müşterilerin yönlendirildiği bir sayfa değildir.
	## 2) Entegrasyonun 1. ADIM'ında gönderdiğniz merchant_oid değeri bu sayfaya POST ile gelir. Bu değeri kullanarak
	## veri tabanınızdan ilgili siparişi tespit edip onaylamalı veya iptal etmelisiniz.
	## 3) Aynı sipariş için birden fazla bildirim ulaşabilir (Ağ bağlantı sorunları vb. nedeniyle). Bu nedenle öncelikle
	## siparişin durumunu veri tabanınızdan kontrol edin, eğer onaylandıysa tekrar işlem yapmayın. Örneği aşağıda bulunmaktadır.

	$post = $_POST;

	####################### DÜZENLEMESİ ZORUNLU ALANLAR #######################
	#
	## API Entegrasyon Bilgileri - Mağaza paneline giriş yaparak BİLGİ sayfasından alabilirsiniz.
	$merchant_key 	= 'YYYYYYYYYYYYYY';
	$merchant_salt	= 'ZZZZZZZZZZZZZZ';
	###########################################################################

	####### Bu kısımda herhangi bir değişiklik yapmanıza gerek yoktur. #######
	#
	## POST değerleri ile hash oluştur.
	$hash = base64_encode( hash_hmac('sha256', $post['merchant_oid'].$merchant_salt.$post['status'].$post['total_amount'], $merchant_key, true) );
	#
	## Oluşturulan hash'i, paytr'dan gelen post içindeki hash ile karşılaştır (isteğin paytr'dan geldiğine ve değişmediğine emin olmak için)
	## Bu işlemi yapmazsanız maddi zarara uğramanız olasıdır.
	if( $hash != $post['hash'] )
		die('PAYTR notification failed: bad hash');
	###########################################################################

	## BURADA YAPILMASI GEREKENLER
	## 1) Siparişin durumunu $post['merchant_oid'] değerini kullanarak veri tabanınızdan sorgulayın.
	## 2) Eğer sipariş zaten daha önceden onaylandıysa veya iptal edildiyse  echo "OK"; exit; yaparak sonlandırın.

	/* Sipariş durum sorgulama örnek
 	   $durum = SQL
	   if($durum == "onay" || $durum == "iptal"){
			echo "OK";
			exit;
		}
	 */

	if( $post['status'] == 'success' ) { ## Ödeme Onaylandı

		## BURADA YAPILMASI GEREKENLER
		## 1) Siparişi onaylayın.
		## 2) Eğer müşterinize mesaj / SMS / e-posta gibi bilgilendirme yapacaksanız bu aşamada yapmalısınız.
		## 3) 1. ADIM'da gönderilen payment_amount sipariş tutarı taksitli alışveriş yapılması durumunda
		## değişebilir. Güncel tutarı $post['total_amount'] değerinden alarak muhasebe işlemlerinizde kullanabilirsiniz.

	} else { ## Ödemeye Onay Verilmedi

		## BURADA YAPILMASI GEREKENLER
		## 1) Siparişi iptal edin.
		## 2) Eğer ödemenin onaylanmama sebebini kayıt edecekseniz aşağıdaki değerleri kullanabilirsiniz.
		## $post['failed_reason_code'] - başarısız hata kodu
		## $post['failed_reason_msg'] - başarısız hata mesajı

	}

	## Bildirimin alındığını PayTR sistemine bildir.
	echo "OK";
	exit;
?>

resources/views/contact.blade.php
@extends('layouts.main')
@section('meta')
    <meta type="keywords" content="Veosnet, İletişim, Telefon, Konum ,Sosyal Medya , Facebook, İnstagram , Twitter">
@endsection
@section('title','VeosNet Network&Marketing || İletişim')
@section('content')
    <div class=" contact_container mx-3" style="margin-top: 150px">

        <script src="//cdn.tinymce.com/4/tinymce.min.js"></script>
        <script>tinymce.init({ selector:'textarea' });</script>
        <ul>
            <a class="mx-3" style="color: black " href="{{route('home')}}">Anasayfa</a> > <a class="mx-3" style="color: gray" title="Geri" onclick="window.history.back()">Geri Git</a>
        </ul>
        <h4 class="text-center mb-5" style="font-family: 'Harlow Solid Italic'">BİZE BURADAN ULAŞABİİRSİNİZ</h4>
        <!-- Map Container -->

        <div class="row">
            <div class="col">
                <div>
                    <div class="">
                        <div class="table-responsive text-center" >
                            <iframe  src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3153.5794617059164!2d29.080669515200544!3d37.776457779759085!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x14c73faf16cfc169%3A0x2b0fd7620ec7a1a0!2sS%C4%B1rakap%C4%B1lar%2C%201585.%20Sk.%20No%3A8%2C%2020010%20Denizli%20Merkez%2FDenizli!5e0!3m2!1str!2str!4v1581623783909!5m2!1str!2str" width="1200" height="500" frameborder="0" style="border:0;border: 5px solid darkslategray; border-radius: 50px" allowfullscreen=""></iframe>
                            <br>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Contact Us -->
         <div class="row">
                <div class="col-lg-6 contact_col">
                <div class="contact_contents">
                    @forelse($iletisim as $i)
                    <p class="mt-4" >Bizi Burada Bulabilirsiniz...</p>
                    <p> {{$i->merkez_adresi}}</p>
                    <div>
                        <p ><i class="fa fa-volume-control-phone font-weight-bold text-dark" ></i> İletişim Numaralarımız</p>
                        <p>-> {{$i->musteri_hatti}}</p>
                        <p>-> {{$i->telefon_hatti}}</p>
                        <br>
                        <p ><i class="fa fa-mail-forward text-dark font-weight-bold" ></i> Öneri ve Şikayetlerinizi Buradanda Gönderebilirsiniz </p>
                            <p> {{$i->email}}</p>
                        <br>
                            <p><i class="fa fa-whatsapp text-success" ></i> Whatsapp Hattımız</p>
                        <p>{{$i->whatsapp}}</p>
                    </div>
                    <div>

                        <br>
                        <p><i class="fa fa-clock-o font-weight-bold" ></i>  Ofis Mesai Saatimiz</p>
                            <p> {{$i->kapanis}} / {{$i->acilis}}</p>
                    </div>
                </div>
                @empty
                        <marquee behavior="" direction="down"> <p class="text-danger">İletişim Alanı Bilgileri Boş Görünüyor...</p></marquee>
                    @endforelse
                </div>
                <!-- Follow Us -->
                <div class="follow_us_contents">
                    @if(Auth::check())
                        <div class="get_in_touch_contents">
                            <h4 style="font-family: 'Harlow Solid Italic'">Bizimle temasa geçebilirsiniz!</h4>
                            <p>Ücretsiz ve gizli bir bilgi almak için aşağıdaki formu doldurunuz.</p>
                            <div class="form-group">
                                <form method="post" action="{{route('message.store')}}">
                                    @csrf
                                    <div class="form-group">
                                        <input id="input_name" class="form_input input_name input_ph" value="{{$user->name}}" type="text" name="name" placeholder="isim " required="required" data-error="Name is required.">
                                    </div>
                                    <div class="form-group">
                                        <input id="input_name" class="form_input input_name input_ph" value="{{$user->surname}}" type="text" name="surname" placeholder="Soyisim" required="required" data-error="Name is required.">
                                    </div>
                                    <div class="form-group">
                                        <input id="input_email" class="form_input input_email input_ph" value="{{$user->email}}" type="email" name="email" placeholder="Email" required="required" data-error="Valid email is required.">
                                    </div>
                                    <div class="form-group">
                                        <textarea id="input_message" class="input_ph input_message" name="message"  placeholder="Mesajınız" rows="3" required data-error="Lütfen bize bir mesaj yazın."></textarea>
                                    </div>
                                    <div class="form-group">
                                        <button class="btn btn-info send-button mx-5" id="submit" type="submit" >
                                            <div class="button">
                                                <i class="fa fa-paper-plane"></i><span class="send-text">GÖNDER</span>
                                            </div>
                                        </button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    @else
                       <div class="get_in_touch_contents">
                           <h4 style="font-family: 'Harlow Solid Italic'">Bizimle temasa geçebilirsiniz!</h4>
                           <p>Ücretsiz ve gizli bir bilgi almak için aşağıdaki formu doldurunuz.</p>
                           <div class="form-group">
                               <form method="post" action="{{route('message.store')}}">
                                   @csrf
                                   <div class="form-group">
                                       <input id="input_name" class="form_input input_name input_ph" type="text" name="name" placeholder="isim " required="required" data-error="Name is required.">
                                   </div>
                                   <div class="form-group">
                                       <input id="input_name" class="form_input input_name input_ph" type="text" name="surname" placeholder="Soyisim" required="required" data-error="Name is required.">
                                   </div>
                                   <div class="form-group">
                                       <input id="input_email" class="form_input input_email input_ph" type="email" name="email" placeholder="Email" required="required" data-error="Valid email is required.">
                                   </div>
                                   <div class="form-group">
                                       <textarea id="input_message" class="input_ph input_message" name="message"  placeholder="Mesajınız" rows="3" required data-error="Lütfen bize bir mesaj yazın."></textarea>
                                   </div>
                                   <div class="form-group">
                                       <button class="btn btn-info send-button mx-5" id="submit" type="submit" >
                                           <div class="button">
                                               <i class="fa fa-paper-plane"></i><span class="send-text">GÖNDER</span>
                                           </div>
                                       </button>
                                   </div>
                               </form>
                           </div>
                       </div>
                    @endif
                </div>
         </div>
        <div class="col-lg-6 get_in_touch_col">
            <h4 class="mt-5 text-center" style="font-family: 'Harlow Solid Italic'">Sosyal Medyada da Birlikte Olmak İsteriz ...</h4>
            @forelse($medya as $m)
            <ul class=" social d-flex flex-row">
                <li><a href='{{$m->facebook}}' style="background-color: #3a61c9"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                <li><a href='{{$m->twitter}}' style="background-color: #41a1f6"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                <li><a href='{{$m->instagram}}' style="background-color: #8f6247"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
                <li><a href="#" style="background-color: #fb4343"><i class="fa fa-google-plus" aria-hidden="true"></i></a></li>
            </ul>
                @empty
                <ul class=" social d-flex flex-row">
                <li><a href='#' style="background-color: #3a61c9"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                <li><a href='#' style="background-color: #41a1f6"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                <li><a href='#' style="background-color: #8f6247"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
                <li><a href="#" style="background-color: #fb4343"><i class="fa fa-google-plus" aria-hidden="true"></i></a></li>
                  </ul>
                <marquee  behavior="" direction="down"> <p class="text-danger">Sosyal Medya Bilgileri Boş Görünüyor...</p></marquee>
                @endforelse
            </div>
    </div>
    </div>
@endsection
@section('js')
    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=AIzaSyCIwF204lFZg1y4kPSIhKaHEXMLYxxuMhA"></script>
    <script src="{{asset('assets/plugins/jquery-ui-1.12.1.custom/jquery-ui.js')}}"></script>
    <script src="{{asset('assets/js/contact_custom.js')}}"></script>
@endsection
@section('css')
    <style>
        .send-button {
            margin-top: 15px;
            height: 34px;
            width: 400px;
            overflow: hidden;
            transition: all .2s ease-in-out;
        }

        .button {
            width: 400px;
            height: 34px;
            transition: all .2s ease-in-out;
        }
        .send-text {
            display: block;
            margin-top: 10px;
            font: 300 14px 'Lato', sans-serif;
            letter-spacing: 2px;
        }

        .button:hover {
            transform: translate3d(0px, -29px, 0px);
        }
    </style>
    <link rel="stylesheet" type="text/css" href="{{asset('assets/plugins/jquery-ui-1.12.1.custom/jquery-ui.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('assets/styles/contact_styles.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('assets/styles/contact_responsive.css')}}">

@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                        Giriş yaptınız!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/kargo.blade.php
@extends("layouts.main")
@section("content")
    <div class="container" style="margin-top: 140px">
        <a class="mx-3" style="color: black " href="{{route('home')}}">Anasayfa</a> > <a class="mx-3" style="color: gray" title="Geri" onclick="window.history.back()">Geri Git</a>
        <h4 class="text-center"style="font-family: 'Harlow Solid Italic'">KARGOM NEREDE ?</h4>
        <br>
        <br>
        <marquee direction="up"  class="text-center" style="font-size: large">Bu Hizmetimiz Şuan Aktif Değildir...</marquee>
        <br>
        <br>
        <br>
        <br>
    </div>

@endsection

@section("customJs")
@endsection

@section("customCss")
@endsection

resources/views/profile.blade.php
@extends('layouts.main')
@section('content')
    <div class=" product_section_container" style="margin-top: 140px">
        <div class="row">
            <div class="col-md-12">
                <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalLabel">Profil Fotoğrafı Yükle</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <div class="form-group">
                                    <form method="post" action="{{route('profil-create.store')}}" enctype="multipart/form-data">
                                        @csrf
                                        <input type="file" name="cover">
                                        <button class="btn btn-outline-dark" style="font-size: small" type="submit">Yükle</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
               @if($varmi == true)
                    <img class="img-fluid float-right mb-3 mx-2"  style="height: 100px;width: 100px;border-radius: 120px" src="{{\Illuminate\Support\Facades\Storage::url($profil_create->cover)}}" alt="">
                   @else
                    <img class="img-fluid float-right mb-3 "  style="height: 100px;width: 100px;border-radius: 60px" src="{{asset('assets/new images/bos-profil.jpg')}}" alt="">
                @endif
                <div class="table-responsive">
                    @if($varmi ==true)
                        <a class="btn btn-outline-warning float-right mx-3" style="font-size: small" onclick="return confirm('Emin Misiniz?')" data-method="delete" href="{{route('psil',$profil_create->id)}}">Profil Fotoğrafımı Kaldır</a>
                        @else
                        <button type="button" class="mx-2 btn btn-outline-info float-right" style="font-size: small" data-toggle="modal" data-target="#exampleModal">
                            Profil Fotoğrafı Yükle
                        </button>
                    @endif
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th>İsim Soyisim</th>
                        <th>E-Mail</th>
                        <th>Adres</th>
                        <th>İban Numarası</th>
                        <th>Cep Telefonu</th>
                        <th>Şehir</th>
                        <th>Ülke</th>
                        <th>Posta Kodu</th>
                        <th>Güncelle</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($userDetails as $userDetail)
                        <tr>
                            <td>{{ $userDetail->user->name }} {{ $userDetail->user->surname }}</td>
                            <td>{{ $userDetail->user->email }}</td>
                            <td>{{ $userDetail->address }} </td>
                            <td>{{ $userDetail->phone }}</td>
                            <td>{{ $userDetail->m_phone }}</td>
                            <td>{{ $userDetail->city }}</td>
                            <td>{{ $userDetail->country }}</td>
                            <td>{{ $userDetail->zipcode }}</td>
                            <td class="text-center">
                                <a href="/profile/{{auth()->user()->id}}/edit" class="btn btn-primary"><i class="fa fa-edit"></i></a>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
                </div>
            </div>
        </div>
    </div>
@endsection