routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/oturum/pmenu', 'HomeController@oturum')->name('pmenu')->middleware('auth','onyedi');
    Route::get('/oturum/hesabim', 'HomeController@hesap')->name('hesap')->middleware('auth','onyedi');
Route::get('/anasayfa/hakkimizda', 'HomeController@hk')->name('hk');
Route::get('/anasayfa/kariyerler', 'HomeController@kariyerler')->name('kariyerler');
Route::get('/veosnet/etkinlikler', 'HomeController@etkinlikler')->name('etkinlikler');
Route::get('/veosnet/misyonumuz ve vizyonumuz', 'HomeController@misyon')->name('misyon');
Route::get('/veosnet/iade şartları', 'HomeController@iade')->name('iade');
Route::get('/', 'HomeController@index')->name('home');
Route::get('/contact', 'HomeController@contact')->name('contact');
Route::get('/category/{slug}', 'HomeController@category')->name('category');
Route::get('/product/{slug}', 'HomeController@product')->name('product');
Route::get('/Kurumsal/Bayi Sozlesmesi ve Prosedurler', 'HomeController@bayi')->name('bayi');
Route::get('/Kurumsal/Temsilcilik Sozlesmesi', 'HomeController@temsilcilik')->name('temsilcilik');
Route::get('/Kurumsal/Gizlilik Sozlesmesi','HomeController@gizlilik')->name('gizlilik');
Route::get('/Kurumsal/Dogrudan Satis Sozlesmesi', 'HomeController@dogrudansatis')->name('dogrudansatis');
Route::get('/Kurumsal/Mesafeli Satis Sozlesmesi', 'HomeController@mesafelisatis')->name('mesafelisatis');
Route::get('/Veosnet/İş Modeli', 'HomeController@ismodeli')->name('ismodeli');
Route::get('/Veosnet/Yeni Urunler', 'HomeController@yeniurunler')->name('yeniurunler');
Route::resource('profil-create','ProfilCreateController');
Route::get('dest/{id}','ProfilCreateController@destroy')->name('psil');
Route::get('/Veosnet/Neden Veosnetwork', 'HomeController@nedenveos')->name('nedenveos');
Route::get('/Veosnet/ProfesyonelPazarlama', 'HomeController@ppazarlama')->name('ppazarlama');
Route::get('/PrimMenu/ekip/', 'PrimController@index')->name('ekipagaci')->middleware('auth','onyedi');
Route::get('/VeosNet/cuzdan', 'PrimController@create')->name('cuzdan')->middleware('auth','onyedi');
Route::get('/VeosNet/binary', 'PrimController@binary')->name('binary')->middleware('auth','onyedi');
Route::get('/VeosNet/binary/datatable', 'PrimController@binary_datatable')->name('binary-datatable')->middleware('auth','onyedi');
Route::get('/VeosNet/kazanc', 'PrimController@store')->name('kazanc')->middleware('auth','onyedi');
Route::get('/PrimMenu/{kid}/kazanc', 'PrimController@gonderme')->name('kid')->middleware('auth','onyedi');
Route::get('/view/Kargo', 'HomeController@kargo')->name('kargo');
Route::get('/view/Odemeplanı', 'HomeController@odemeplanı')->name('odemeplanı');
Route::get('/view/basari', 'HomeController@basari')->name('basari');
Route::get('/view/profesyonel_pazarlama', 'HomeController@profesyonelpazarlama')->name('profesyonelpazarlama');
Route::get('/view/genelbakis', 'PrimController@genelbakis')->name('genelbakis')->middleware('auth','onyedi');
Route::get("/view/menu","PrimController@menu")->name('menu')->middleware('auth','onyedi');
Route::get('/view/guvenliodeme','HomeController@cartman')->name('cartman')->middleware('auth','onyedi');
Route::get('/view/TarimOnaylidir','HomeController@tarimbelge')->name('tarimbelge');
Route::get('/view/Kazancozeti','HomeController@kazancozeti')->name('kazancozeti')->middleware('auth','onyedi');
Route::get('/VeosNet/Kazancozeti/datatable','GelirController@kazancozeti_datatable')->name('kazancozeti.datatable')->middleware('auth','onyedi');
Route::get('/VeosNet/gelenpv/datatable','GelenpvController@gelenpv_datatable')->name('gelenpv.datatable')->middleware('auth','onyedi');
Route::get('Veosnet/Pv/Cv Gelirlerim','GelenpvController@index')->name('gelenpvsyf');
Route::get('/VeosNet/gelirlerim','HomeController@gelirlerim')->name('gelirlerim')->middleware('auth','onyedi');
Route::get('VeosNet/S.S.S','HomeController@sss')->name('sss');
Route::resource('mailorder','MailOrderController');
Route::get('Kampanyalar','HomeController@kampanyalar')->name('kampanyalar');
Route::get('haberlerimiz','HomeController@haber2')->name('haberler2');
Route::get('Bilgilendirme','HomeController@bilgilendirme')->name('bilgilendirme21')->middleware('auth','onyedi');
Route::get('hesapbilgileri','HomeController@banka')->name('banka')->middleware('auth','onyedi');
Route::get('VeosNet/Sozlesmeler','HomeController@sozlesmemusteri')->name('sozlesmemusteri');
Route::get('VeosNet/sozlesmelerimiz/{uuid}/download','HomeController@download')->name('sozlesme.download')->middleware('auth');
Route::get('VeosNet/kullaniciilcirosu','HomeController@il_ciro')->name('il_ciro')->middleware('auth','onyedi');
Route::get('VeosNet/kullanicitrciro','HomeController@tr_ciro')->name('tr_ciro')->middleware('auth','onyedi');
Route::get('VeosNet/kullanicidunyaciro','HomeController@dunya_ciro')->name('dunya_ciro')->middleware('auth','onyedi');
Route::get('VeosNet/kullaniciarabaciro','HomeController@araba_ciro')->name('araba_ciro')->middleware('auth','onyedi');
Route::get('VeosNet/kullanicibolgeciro','HomeController@bolge_ciro')->name('bolge_ciro')->middleware('auth','onyedi');
Route::get('veosnet/GuvenliOdeme','HomeController@mailorder')->name('mailorder');
Route::resource('VeosNet/odemetalebi','OdemeTalebiController')->middleware('auth','onyedi');
Route::resource('message','MessageController');
Route::get('/Veosnet/Kataloglar','HomeController@kullanici_katalog')->name('kullanici_katalog');

Route::group(['namespace'=>"Admin"],function (){
    Route::get('/VeosNet/kullanici/katalog/{uuid}/download', 'KatalogController@download')->name('katalog.download');
});
Route::get('VeosNet/EftDurum','HomeController@musteri_eft_durum')->name('musteri_eft_durum')->middleware('auth','onyedi');

Route::get('veosnet/alt-uyelik-ekle','PrimController@farkli_il_kayit_index')->middleware('auth')->name('yeni-alt-bayi');
Route::post('veosnet/alt-uyelik-ekle','PrimController@farkli_il_kayit_store')->middleware('auth')->name('yeni-alt-bayi.store');
Route::get('veosnet/alt-uyeliklerim','PrimController@alt_bayiliklerim')->middleware('auth')->name('alt-bayiliklerim');

Route::get('logout','Auth\LoginController@logout');
    //Route::get('kayit/{konum}','uyelikController@index')->name('kayityapma');
Route::get('kayit/{konum}/{sps}','uyelikController@index')->name('kayityapma')->middleware('auth');
Route::post('kayit','uyelikController@store')->name('kayityapma.kayıt')->middleware('auth');
Route::get('KonumBilgilendirme','PrimController@bilgilendirme')->name('bilgilendirme')->middleware('auth');
Route::get('isteklerim','PrimController@isteklerim')->name('isteklerim')->middleware('auth');
Route::get('ekiptakip','PrimController@ekiptakip')->name('ekiptakip')->middleware('auth');
Route::get('ekiplistesi','PrimController@ekiplistesi')->name('ekiplistesi')->middleware('auth');
Route::get('change-password', 'ChangePasswordController@index')->name('change')->middleware('auth');
Route::post('change-password', 'ChangePasswordController@store')->name('change.password')->middleware('auth');
Route::post('konumlandirin/{ikid}','Admin\TransferController@iskonum')->name('iskonum')->middleware('auth');

Route::post('odeme-cuzdan/{tutar}','GelirController@cuzdanOdeme')->name('cuzdan.odeme')->middleware('auth');
Route::get('bankahesapbilgileri','PrimController@bankahesapbilgileri')->name('bankahesapbilgileri')->middleware('auth');
Route::get('bankahesapbilgileri/{order_no}','PrimController@bankahesapbilgilerikisiyeozel')->name('bankahesapbilgileri.kisiyeozel')->middleware('auth');


Route::group(["middleware" => ["is_thisAdmin","auth"]],function (){
    Route::group(["namespace" => "Admin"], function (){
        Route::resource("admin-users","UsersController");
        Route::get("admin-users/datatable/d","UsersController@users_datatable")->name('admin-users.datatable');
        Route::get("admin-users/datatable/active","UsersController@users_active_datatable")->name('admin-users.active.datatable');
        Route::get("admin-users/datatable/pasive","UsersController@users_passive_datatable")->name('admin-users.passive.datatable');
        Route::resource("admin-category","CategoryController");
        Route::resource("admin-products","ProductController");
        Route::resource("admin-orders","OrderController");
        Route::resource('kariyer','KariyerController');
        Route::resource('transfer','TransferController');
        Route::get('Binarykontrol','TransferController@adminagac')->name('binarykontrol');
        Route::post('admin/admin-pv/{id}/ekle','TransferController@admin_pv_ekleme')->name('admin.pv.ekle');
        Route::post('admin/admin-cv/{id}/ekle','TransferController@admin_cv_ekleme')->name('admin.cv.ekle');
        Route::get('AdminEkiplistesi','TransferController@adminekip')->name('adminekip');
        Route::get('transfer/{id}/sil','TransferController@destroy2')->name('transfersilme');
        Route::post('transfer/{tid}','TransferController@transferet')->name('transfer');
        Route::post('konumlandir/{kdid}','TransferController@konumlandir')->name('konumlandir');
        Route::get('kontrolmenu','TransferController@kontrolmenu')->name('kontrolmenu');
        Route::get('aktif_pasif','TransferController@aktif')->name('aktif');
        Route::get('users-pasif','TransferController@pasif')->name('users.passive');
        Route::get('aracciro','TransferController@araciro')->name('adminaraciro');
        Route::get('tazminat','TransferController@tazminat')->name('tazminat');
        Route::get('tazminat/{id}','TransferController@tazminatode')->name('tazminat-ode');

resources/views/layouts/prim_menu/cuzdan.blade.php
@extends("layouts.main")
@section("content")
                 <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
                 <link rel="stylesheet" href="{{asset('css/menu.css')}}">

                 <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
                 <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>

                 <div class=""style="margin-top: 70px;background-image: url('https://cutewallpaper.org/21/white-hd-wallpaper/Abstract-Wallpaper-White.jpg')" >
                     <div class="col-md-12 mb-2 " >
                         <div class="row">
                             <div class="col-md-6 mt-3 ">
                                 <p style="color: black"><i class="fa fa-user mx-3 "></i>Sayın;&nbsp; {{auth()->user()->name}} {{auth()->user()->surname}}</p>
                                 <p style="color: black"><i class="fa fa-user-secret mx-3"></i>Kullanıcı Numaranız: [ {{auth()->user()->id}} ]</p>
                             </div>
                             <div class="col-md-6 mt-3">
                                 <p class=" mt-2 mx-5"style="color: black"><i class="fa fa-briefcase mx-3"></i> Kariyeriniz :&nbsp; {{auth()->user()->kariyer->kariyername}}</p>
                                 <p class="mx-5"  style="color: black"> <i class="fa fa-battery-quarter mx-3"></i>Şuan ki Kariyer Puanınız :&nbsp; {{auth()->user()->ara_pv}} PV</p>
                             </div>
                         </div>
                         <div style="height: 1px;background-image: url('https://wallpaperaccess.com/full/1216046.jpg')"></div>
                     </div>
                     <div class="row">
                         <div class="col-md-12">
                             <div class="col-md-3">
                                 <ul id="menu-v">
                                     <li>  <h5 class="arrow text-white  text-center">CÜZDAN BAKİYENİZ</h5></li>
                                     <li><a class=""title="Geri" onclick="window.history.back()">Geri Gitmek İstiyorum</a></li>
                                     <li>
                                         <a class="arrow" href="#">Genel Bakış</a>
                                         <ul>
                                             <li>
                                                 <a class="" href="{{route('alt-bayiliklerim')}}">
                                                     İllerdeki Bayiliklerim
                                                 </a>
                                             </li>
                                             <li>
                                                 <a  class="" href="{{route('yeni-alt-bayi')}}">
                                                     Yeni İlde Bayi Aç
                                                 </a>
                                             </li>
                                         </ul>
                                     </li>
                                     <li><a href= "{{route("kazanc")}}"> Ekibim</a>
                                     <li><a href="{{route('binary')}}"> Soy Ağacı Kazancım</a></li>
                                     <li> <a href="{{route("cuzdan")}}"> Cüzdanım</a></li>
                                     <li><a  href="{{route("isteklerim")}}"> İsteklerim</a></li>
                                     <li><a href="{{route("kazancozeti")}}">Gelirlerim</a> </li>
                                     <li> <a  href="{{route("gelenpvsyf")}}"> Pv/Cv Gelirlerim</a></li>
                                     <li><a href="{{route("hesap")}}">Hesap Menü</a></li>
                                 </ul>
                             </div>
                             <div class="col-md-9" >
                                 <div class=" offset-l3 z-depth-4 s12 m12">
                                     <h4 style="font-family: 'Harlow Solid Italic'"></h4>
                                     <hr>
                                     <ul id="tabs-swipe-demo" class="tabs d-inline-flex ">
                                         <li class="tab col-3 s3"><a class="text-secondary" href="#btc"><strong>Bakiyem</strong></a></li>
                                         <li class="tab col-3 s3" style="border-left: 2px solid #dc3545"><a class="text-secondary"  href="#eth"><strong>Brüt Bakiyem</strong></a></li>
                                         <li class="tab col-3 s3" style="border-left: 2px solid #dc3545"><a class="text-secondary"  href="#neo"><strong>Alınan Ödeme</strong></a></li>
                                         <li class="tab col-3 s3" style="border-left: 2px solid #dc3545"><a class="text-secondary"  href="#stx"><strong >Ödeme Talebi</strong></a></li>
                                     </ul>
                                     <div id="btc" class="col s12 mt-5 w-75">
                                         <div class="row">
                                             <div class="col s12 m12">
                                                 <div class="card no-shadows alert alert-info">
                                                     <div class="card-content ">
                                                         <h4 style="font-family: 'Harlow Solid Italic'" class="card-title">Cüzdan Bakiyeniz</h4>
                                                         <p>{{$cuzdan->toplam_bakiye}} <small> ₺</small></p>
                                                     </div>
                                                 </div>
                                             </div>
                                         </div>
                                     </div>
                                     <div id="eth" class="col s12 mt-5 w-75">
                                         <div class="row">
                                             <div class="col s12 m12">
                                                 <div class="card no-shadows alert alert-success">
                                                     <div class="card-content ">
                                                         <h4 style="font-family: 'Harlow Solid Italic'" class="card-title">Bakiyenizin %20 Kesinti Gösterimi</h4>
                                                         @php $odenen=(auth()->user()->cuzdan->toplam_bakiye ) - ((auth()->user()->cuzdan->toplam_bakiye )*20)/100; @endphp
                                                         {{$odenen}} <small> ₺</small>
                                                     </div>
                                                 </div>
                                             </div>
                                         </div>
                                     </div>

                                     <div id="neo" class="col s12 mt-5 w-75">
                                         <div class="row">
                                             <div class="col s12 m12">
                                                 <div class="card no-shadows alert alert-success">
                                                     <div class="card-content ">
                                                         <h4 style="font-family: 'Harlow Solid Italic'" class="card-title mb-3">Hesabınıza Yatırılan Toplam Tutar </h4>
                                                         {{$cuzdan->odenen_bakiye}} <small> ₺</small>
                                                     </div>
                                                 </div>
                                             </div>
                                         </div>
                                     </div>

                                     <div id="stx" class="col s12 mt-5 w-75">
                                         <div class="row">
                                             <div class="col s12 m12 ">
                                                 <div class="card no-shadows alert alert-success">
                                                     <div class="card-content ">
                                                         <h4 class="card-title mb-2" style="font-family: 'Harlow Solid Italic'">Ödeme Talebinde Bulunmak mı İstiyorsunuz ?</h4>
                                                         <a class=" w-25 btn btn-info mt-3 mb-3 mx-5" href="{{route('odemetalebi.create')}}">EVET</a>
                                                     </div>
                                                 </div>
                                             </div>
                                         </div>
                                     </div>
                                 </div>
                             </div>
                         </div>
                    </div>
                </div>
@endsection
@section("js")
    <!--Import jQuery before materialize.js-->
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function(){
            $('.tabs').tabs();
        });

    </script>

@endsection
@section("css")
    <link rel="stylesheet" href="{{asset('css/cuzdan.css')}}">
@endsection

resources/views/layouts/prim_menu/ekibim.blade.php
@extends("layouts.main")
@section("content")
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <!------ Include the above in your HEAD tag ---------->

    <div class="container"  style="margin-top: 170px">
        <div class="row">
            <div class="col-md-12">
              <div class="col-md-3">
                  <div class="panel-group" id="accordion">
                      <div class="panel panel-default">
                          <div style="background: #ff820e" class="panel-heading">
                              <h4 class="panel-title">

                                  <a style="color: #EFEFEF">  PRİM MENÜ</a>
                              </h4>
                          </div>
                          <div id="collapseOne" class="panel-collapse collapse in">
                              <div class="panel-body">
                                  <table class="table">
                                      <tr>
                                          <td>
                                              <span class="glyphicon glyphicon-eye-open text-primary"></span><a href="http://www.jquery2dotnet.com">Genel Bakış</a>
                                          </td>
                                      </tr>
                                      <tr>
                                          <td>
                                              <span class="fa fa-users text-success"> </span><a href="{{route("ekipagaci")}}"> Ekibim</a>
                                          </td>
                                      </tr>
                                      <tr>
                                          <td>
                                              <span class="fa fa-money text-info"></span><a href="http://www.jquery2dotnet.com"> Gelirlerim</a>
                                          </td>
                                      </tr>
                                      <tr>
                                          <td>
                                              <span class="fa fa-google-wallet text-success"></span><a href="{{route("cuzdan")}}"> Cüzdanım</a>

                                          </td>
                                      </tr>
                                      <tr>
                                          <td>
                                              <span class="glyphicon glyphicon-stats text-success"></span><a href="http://www.jquery2dotnet.com">Kazanç Özetim</a>

                                          </td>
                                      </tr>
                                      <tr>
                                          <td>
                                              <span class="fa fa-server text-success"></span><a href="http://www.jquery2dotnet.com"> Hesap Menü</a>

                                          </td>
                                      </tr>
                                  </table>
                              </div>
                          </div>
                      </div>
                  </div>

              </div>
            </div>

        </div>
      </div>
@endsection

@section("customJs")
@endsection

@section("customCss")
@endsection

resources/views/layouts/prim_menu/ekipagaci.blade.php
@extends("layouts.main")
@section("content")
    <br>
    <br>
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <!------ Include the above in your HEAD tag ---------->
    <div class="container"  style="margin-top: 170px">
        <div class="row">
            <div class="col-sm-3 col-md-3">
                <div class="panel-group" id="accordion">
                    <div class="panel panel-default">
                        <div style="background: #ff820e" class="panel-heading">
                            <h4 class="panel-title">

                                <a style="color: #EFEFEF">  PRİM MENÜ</a>
                            </h4>
                        </div>
                        <div id="collapseOne" class="panel-collapse collapse in">
                            <div class="panel-body">
                                <table class="table">
                                    <tr>
                                        <td>
                                            <span class="glyphicon glyphicon-eye-open text-primary"></span><a href="http://www.jquery2dotnet.com">Genel Bakış</a>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <span class="fa fa-users text-success"> </span><a href="{{route("ekipagaci")}}"> Ekibim</a>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <i class="text-success fa fa-tree"></i> <a href="{{route('binary')}}"> Binary Kazancım</a>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <span class="fa fa-google-wallet text-success"></span><a href="{{route("cuzdan")}}"> Cüzdanım</a>

                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <span class="glyphicon glyphicon-stats text-success"></span><a href="http://www.jquery2dotnet.com">Kazanç Özetim</a>

                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <span class="fa fa-server text-success"></span><a href="http://www.jquery2dotnet.com"> Hesap Menü</a>

                                        </td>
                                    </tr>
                                </table>
                            </div>
                        </div>
                    </div>


    <div class="row justify-content-center" style="margin-left: 375px">
        <div class="col-12">
            <br>
            <br>
           &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <button class="fa fa-user-plus" style="height: 42px;width:45px"></button>
            @for($i=0;$i<8;$i++)
                <div class="row justify-content-center">
                    <div class="col-12">
                    @for($j=0;$j<8;$j++)
                        <div class="btn btn-sm btn btn-outline-primary ml-3 my-5">
                           <p class="fa fa-user-plus"></p>
                        </div>
                    @endfor
                    </div>
                </div>
                @endfor
        </div>
    </div>
</div>




@endsection

@section("customJs")


@endsection

@section("customCss")


@endsection

resources/views/layouts/prim_menu/gelirlerim.blade.php
@extends("layouts.main")
@section("content")
    <br>
    <br>
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <link rel="stylesheet" href="{{asset('css/menu.css')}}">
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <!------ Include the above in your HEAD tag ---------->
    <div class="container"  style="margin-top: 170px">
        <div class="row">
            <div class="col-md-4">
                <div class="panel-group" id="accordion">
                    <div class="panel panel-default">
                        <div style="background: #ff820e" class="panel-heading">
                            <h4 class="panel-title">

                                <a style="color: #EFEFEF">  PRİM MENÜ</a>
                            </h4>
                        </div>
                        <div id="collapseOne" class="panel-collapse collapse in">
                            <div class="panel-body">
                                <table class="table">
                                    <tr>
                                        <td>
                                            <span class="glyphicon glyphicon-eye-open text-primary"></span><a href="http://www.jquery2dotnet.com">Genel Bakış</a>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <span class="fa fa-users text-success"> </span><a href="{{route("ekipagaci")}}"> Ekibim</a>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <span class="fa fa-money text-info"></span><a href="http://www.jquery2dotnet.com"> Gelirlerim</a>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <span class="fa fa-google-wallet text-success"></span><a href="{{route("cuzdan")}}"> Cüzdanım</a>

                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <span class="glyphicon glyphicon-stats text-success"></span><a href="http://www.jquery2dotnet.com">Kazanç Özetim</a>

                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <span class="fa fa-server text-success"></span><a href="http://www.jquery2dotnet.com"> Hesap Menü</a>

                                        </td>
                                    </tr>
                                </table>
                            </div>
                        </div>
                    </div>
@endsection

@section("customJs")
@endsection

@section("customCss")
@endsection