routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/oturum/pmenu', 'HomeController@oturum')->name('pmenu')->middleware('auth','onyedi');
    Route::get('/oturum/hesabim', 'HomeController@hesap')->name('hesap')->middleware('auth','onyedi');
Route::get('/anasayfa/hakkimizda', 'HomeController@hk')->name('hk');
Route::get('/anasayfa/kariyerler', 'HomeController@kariyerler')->name('kariyerler');
Route::get('/veosnet/etkinlikler', 'HomeController@etkinlikler')->name('etkinlikler');
Route::get('/veosnet/misyonumuz ve vizyonumuz', 'HomeController@misyon')->name('misyon');
Route::get('/veosnet/iade şartları', 'HomeController@iade')->name('iade');
Route::get('/', 'HomeController@index')->name('home');
Route::get('/contact', 'HomeController@contact')->name('contact');
Route::get('/category/{slug}', 'HomeController@category')->name('category');
Route::get('/product/{slug}', 'HomeController@product')->name('product');
Route::get('/Kurumsal/Bayi Sozlesmesi ve Prosedurler', 'HomeController@bayi')->name('bayi');
Route::get('/Kurumsal/Temsilcilik Sozlesmesi', 'HomeController@temsilcilik')->name('temsilcilik');
Route::get('/Kurumsal/Gizlilik Sozlesmesi','HomeController@gizlilik')->name('gizlilik');
Route::get('/Kurumsal/Dogrudan Satis Sozlesmesi', 'HomeController@dogrudansatis')->name('dogrudansatis');
Route::get('/Kurumsal/Mesafeli Satis Sozlesmesi', 'HomeController@mesafelisatis')->name('mesafelisatis');
Route::get('/Veosnet/İş Modeli', 'HomeController@ismodeli')->name('ismodeli');
Route::get('/Veosnet/Yeni Urunler', 'HomeController@yeniurunler')->name('yeniurunler');
Route::resource('profil-create','ProfilCreateController');
Route::get('dest/{id}','ProfilCreateController@destroy')->name('psil');
Route::get('/Veosnet/Neden Veosnetwork', 'HomeController@nedenveos')->name('nedenveos');
Route::get('/Veosnet/ProfesyonelPazarlama', 'HomeController@ppazarlama')->name('ppazarlama');
Route::get('/PrimMenu/ekip/', 'PrimController@index')->name('ekipagaci')->middleware('auth','onyedi');
Route::get('/VeosNet/cuzdan', 'PrimController@create')->name('cuzdan')->middleware('auth','onyedi');
Route::get('/VeosNet/binary', 'PrimController@binary')->name('binary')->middleware('auth','onyedi');
Route::get('/VeosNet/binary/datatable', 'PrimController@binary_datatable')->name('binary-datatable')->middleware('auth','onyedi');
Route::get('/VeosNet/kazanc', 'PrimController@store')->name('kazanc')->middleware('auth','onyedi');
Route::get('/PrimMenu/{kid}/kazanc', 'PrimController@gonderme')->name('kid')->middleware('auth','onyedi');
Route::get('/view/Kargo', 'HomeController@kargo')->name('kargo');
Route::get('/view/Odemeplanı', 'HomeController@odemeplanı')->name('odemeplanı');
Route::get('/view/basari', 'HomeController@basari')->name('basari');
Route::get('/view/profesyonel_pazarlama', 'HomeController@profesyonelpazarlama')->name('profesyonelpazarlama');
Route::get('/view/genelbakis', 'PrimController@genelbakis')->name('genelbakis')->middleware('auth','onyedi');
Route::get("/view/menu","PrimController@menu")->name('menu')->middleware('auth','onyedi');
Route::get('/view/guvenliodeme','HomeController@cartman')->name('cartman')->middleware('auth','onyedi');
Route::get('/view/TarimOnaylidir','HomeController@tarimbelge')->name('tarimbelge');
Route::get('/view/Kazancozeti','HomeController@kazancozeti')->name('kazancozeti')->middleware('auth','onyedi');
Route::get('/VeosNet/Kazancozeti/datatable','GelirController@kazancozeti_datatable')->name('kazancozeti.datatable')->middleware('auth','onyedi');
Route::get('/VeosNet/gelenpv/datatable','GelenpvController@gelenpv_datatable')->name('gelenpv.datatable')->middleware('auth','onyedi');
Route::get('Veosnet/Pv/Cv Gelirlerim','GelenpvController@index')->name('gelenpvsyf');
Route::get('/VeosNet/gelirlerim','HomeController@gelirlerim')->name('gelirlerim')->middleware('auth','onyedi');
Route::get('VeosNet/S.S.S','HomeController@sss')->name('sss');
Route::resource('mailorder','MailOrderController');
Route::get('Kampanyalar','HomeController@kampanyalar')->name('kampanyalar');
Route::get('haberlerimiz','HomeController@haber2')->name('haberler2');
Route::get('Bilgilendirme','HomeController@bilgilendirme')->name('bilgilendirme21')->middleware('auth','onyedi');
Route::get('hesapbilgileri','HomeController@banka')->name('banka')->middleware('auth','onyedi');
Route::get('VeosNet/Sozlesmeler','HomeController@sozlesmemusteri')->name('sozlesmemusteri');
Route::get('VeosNet/sozlesmelerimiz/{uuid}/download','HomeController@download')->name('sozlesme.download')->middleware('auth');
Route::get('VeosNet/kullaniciilcirosu','HomeController@il_ciro')->name('il_ciro')->middleware('auth','onyedi');
Route::get('VeosNet/kullanicitrciro','HomeController@tr_ciro')->name('tr_ciro')->middleware('auth','onyedi');
Route::get('VeosNet/kullanicidunyaciro','HomeController@dunya_ciro')->name('dunya_ciro')->middleware('auth','onyedi');
Route::get('VeosNet/kullaniciarabaciro','HomeController@araba_ciro')->name('araba_ciro')->middleware('auth','onyedi');
Route::get('VeosNet/kullanicibolgeciro','HomeController@bolge_ciro')->name('bolge_ciro')->middleware('auth','onyedi');
Route::get('veosnet/GuvenliOdeme','HomeController@mailorder')->name('mailorder');
Route::resource('VeosNet/odemetalebi','OdemeTalebiController')->middleware('auth','onyedi');
Route::resource('message','MessageController');
Route::get('/Veosnet/Kataloglar','HomeController@kullanici_katalog')->name('kullanici_katalog');

Route::group(['namespace'=>"Admin"],function (){
    Route::get('/VeosNet/kullanici/katalog/{uuid}/download', 'KatalogController@download')->name('katalog.download');
});
Route::get('VeosNet/EftDurum','HomeController@musteri_eft_durum')->name('musteri_eft_durum')->middleware('auth','onyedi');

Route::get('veosnet/alt-uyelik-ekle','PrimController@farkli_il_kayit_index')->middleware('auth')->name('yeni-alt-bayi');
Route::post('veosnet/alt-uyelik-ekle','PrimController@farkli_il_kayit_store')->middleware('auth')->name('yeni-alt-bayi.store');
Route::get('veosnet/alt-uyeliklerim','PrimController@alt_bayiliklerim')->middleware('auth')->name('alt-bayiliklerim');

Route::get('logout','Auth\LoginController@logout');
    //Route::get('kayit/{konum}','uyelikController@index')->name('kayityapma');
Route::get('kayit/{konum}/{sps}','uyelikController@index')->name('kayityapma')->middleware('auth');
Route::post('kayit','uyelikController@store')->name('kayityapma.kayıt')->middleware('auth');
Route::get('KonumBilgilendirme','PrimController@bilgilendirme')->name('bilgilendirme')->middleware('auth');
Route::get('isteklerim','PrimController@isteklerim')->name('isteklerim')->middleware('auth');
Route::get('ekiptakip','PrimController@ekiptakip')->name('ekiptakip')->middleware('auth');
Route::get('ekiplistesi','PrimController@ekiplistesi')->name('ekiplistesi')->middleware('auth');
Route::get('change-password', 'ChangePasswordController@index')->name('change')->middleware('auth');
Route::post('change-password', 'ChangePasswordController@store')->name('change.password')->middleware('auth');
Route::post('konumlandirin/{ikid}','Admin\TransferController@iskonum')->name('iskonum')->middleware('auth');

Route::post('odeme-cuzdan/{tutar}','GelirController@cuzdanOdeme')->name('cuzdan.odeme')->middleware('auth');
Route::get('bankahesapbilgileri','PrimController@bankahesapbilgileri')->name('bankahesapbilgileri')->middleware('auth');
Route::get('bankahesapbilgileri/{order_no}','PrimController@bankahesapbilgilerikisiyeozel')->name('bankahesapbilgileri.kisiyeozel')->middleware('auth');


Route::group(["middleware" => ["is_thisAdmin","auth"]],function (){
    Route::group(["namespace" => "Admin"], function (){
        Route::resource("admin-users","UsersController");
        Route::get("admin-users/datatable/d","UsersController@users_datatable")->name('admin-users.datatable');
        Route::get("admin-users/datatable/active","UsersController@users_active_datatable")->name('admin-users.active.datatable');
        Route::get("admin-users/datatable/pasive","UsersController@users_passive_datatable")->name('admin-users.passive.datatable');
        Route::resource("admin-category","CategoryController");
        Route::resource("admin-products","ProductController");
        Route::resource("admin-orders","OrderController");
        Route::resource('kariyer','KariyerController');
        Route::resource('transfer','TransferController');
        Route::get('Binarykontrol','TransferController@adminagac')->name('binarykontrol');
        Route::post('admin/admin-pv/{id}/ekle','TransferController@admin_pv_ekleme')->name('admin.pv.ekle');
        Route::post('admin/admin-cv/{id}/ekle','TransferController@admin_cv_ekleme')->name('admin.cv.ekle');
        Route::get('AdminEkiplistesi','TransferController@adminekip')->name('adminekip');
        Route::get('transfer/{id}/sil','TransferController@destroy2')->name('transfersilme');
        Route::post('transfer/{tid}','TransferController@transferet')->name('transfer');
        Route::post('konumlandir/{kdid}','TransferController@konumlandir')->name('konumlandir');
        Route::get('kontrolmenu','TransferController@kontrolmenu')->name('kontrolmenu');
        Route::get('aktif_pasif','TransferController@aktif')->name('aktif');
        Route::get('users-pasif','TransferController@pasif')->name('users.passive');
        Route::get('aracciro','TransferController@araciro')->name('adminaraciro');
        Route::get('tazminat','TransferController@tazminat')->name('tazminat');
        Route::get('tazminat/{id}','TransferController@tazminatode')->name('tazminat-ode');

resources/views/admin/AltAlanCreate.blade.php
@extends('layouts.main')

@section('content')
    <div class="container-fluid" style="margin-top: 150px">
        <script src="//cdn.tinymce.com/4/tinymce.min.js"></script>
        <script>tinymce.init({ selector:'textarea' });</script>
        <!-- Modal -->
        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Bilgilendirme</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <p></p>
                    </div>
                </div>
            </div>
        </div>
        <a class="" style="color: black " href="{{route('home')}}">Anasayfa</a> > <a class="mx-3" style="color: gray" title="Geri" onclick="window.history.back()">Geri Git</a>
        <button style="font-size: small" type="button" class="btn btn-outline-warning mx-4" data-toggle="modal" data-target="#exampleModal">Bilgilendirme</button>
        <div class="col-md-12 mt-3">
            <div class="form-group">
                <form action="{{ route('alt-alan.store')}}" method="POST" enctype="multipart/form-data">
                    @csrf
                    <div class="col-md-12">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <small>1.Alan</small>
                                    <textarea name="bir" id="" cols="90" rows="12"></textarea>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <small>2.Alan </small>
                                    <textarea name="iki" id="" cols="90" rows="12"></textarea>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <small> 3.Alan</small>
                                    <textarea name="uc" id="" cols="90" rows="12"></textarea>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <small>4.Alan</small>
                                    <textarea name="dort" id="" cols="90" rows="12"></textarea>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Kaydet " class="btn btn-info w-50 mt-5 mx-5">
                    </div>
                </form>
            </div>
        </div>


    </div>
@endsection
@section('js')

@endsection

resources/views/admin/addkariyer.blade.php
@extends('layouts.main')
@section("content")
    <div class="container " style="padding: 30px;margin-top: 170px">
        <h3 class="text-center" style="font-family: 'Harlow Solid Italic'">Kariyer Ekleme Ekranı</h3>
        <br>
        <div class="row">
            <div class="col-md-12">
                {!!Form::open(['url' => route('kariyer.store'),'files' => 'true', "method" => "post"]) !!}
                {!! Form::bsText("kariyername","Kariyer İsmi") !!}
                {!! Form::bsText("tutar","Paket Alt Limiti") !!}
                {!! Form::bsText("sponsor","Sponsor %") !!}
                {!! Form::bsText("indirim"," Alışveriş") !!}
                {!! Form::bsText("binary"," Binary") !!}
                {!! Form::bsText("il_ciro","") !!}
                {!! Form::bsText("tr_ciro","Türkiye Ciro") !!}
                {!! Form::bsText("dunya_ciro","Dünya Ciro") !!}
                {!! Form::bsText("araba_ciro","") !!}
                {!! Form::bsText("bolge_ciro","") !!}
                {!! Form::bsText("lider_primi","") !!}
                {!! Form::bsText("derinlik_birinci_derinlik"," Birinci Derinlik") !!}
                {!! Form::bsSubmit("Kaydet") !!}
                {!! Form::close() !!}

            </div>
        </div>
    </div>
@endsection

@section("customJs")
@endsection

@section("customCss")
@endsection

resources/views/admin/dunya_ciro.blade.php
@extends('layouts.main')
@section("content")
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <link rel="stylesheet" href="{{asset('css/menu.css')}}">
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <div class="container" style="margin-top: 170px">
        <div class="row">
            <div class="col-md-12">
                <div class="col-md-3">
                    <div class="panel-group" id="accordion">
                        <div class="panel panel-default">
                            <div style="background: black" class="panel-heading">
                                <h4 class="panel-title">
                                    <a style="color: white"  href="{{route('menu')}}"></a> <a style="color: #EFEFEF"> KONTROL MENÜ</a>
                                </h4>
                            </div>
                            <div id="collapseOne" class="panel-collapse collapse in">
                                <div class="panel-body ">
                                    <table class="table">
                                        <tr>
                                            <td>
                                                <span class="fa fa-play text-dark"></span><a
                                                        href="{{route("aktif")}}"> Aktif-Pasif Kullanıcılar</a>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <span class="fa fa-car text-dark"> </span><a
                                                        href="{{route("adminaraciro")}}"> Araba Cirosu Alacaklar</a>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <span class="fa fa-money text-dark"></span><a
                                                        href="{{route('tazminat')}}"> Tazminat Alacaklar</a>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <span class="fa fa-google-wallet text-dark"></span><a
                                                        href="{{route("adminilciro")}}"> İL Cirosu Alacaklar</a>

                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <span class="fa fa-google-wallet text-dark"></span><a
                                                        href="{{route("adminturkeyciro")}}"> Türkiye Cirosu Alacaklar</a>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <span class="fa fa-google-wallet text-dark"></span><a
                                                        href="{{route("admindunyaciro")}}"> Dünya Cirosu Alacaklar</a>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <span class="fa fa-google-wallet text-dark"></span><a
                                                        href="{{route("adminbolgeciro")}}"> Bölge Cirosu Alacaklar</a>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <span class="fa fa-server text-dark"></span><a href="{{route("kontrolmenu")}}">
                                                    Kontrol Menü</a>

                                            </td>
                                        </tr>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-9">
                    <h4 class="text-center " STYLE="font-family: 'Harlow Solid Italic'">DÜNYA CİROSU ALACAK KULLANICILAR</h4>
                    <div class="table-responsive">
                        <table class="table table-bordered table-hover mt-5">
                                    <tr>
                                        <th>Kullanıcı Numarası</th>
                                        <th>İsim Soyisim </th>
                                        <th>İletişim</th>
                                        <th>Kariyeri</th>
                                        <th>Tutar</th>
                                    </tr>
                            @foreach($dunya_ciro as $gelir)
                                <tr>
                                    <td>{{$gelir->user->id}}</td>
                                    <td>{{$gelir->user->name}} {{$gelir->user->surname}}</td>
                                    <td>{{$gelir->user->telefon}} / {{$gelir->user->email}}</td>
                                    <td>{{$gelir->user->kariyer->kariyername}}</td>
                                    <td> {{$gelir->kazanc_miktari}}₺</td>
                                </tr>
                            @endforeach
                        </table>
                        {{$dunya_ciro->links()}}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section("js")
@endsection

@section("css")
@endsection

resources/views/admin/duyuru_edit.blade.php
@extends('layouts.main')
@section("content")
    <div class="container " style="padding: 30px;margin-top: 170px">
        <h3 class="text-center" style="font-family: 'Harlow Solid Italic'">Duyuru Güncelleme Ekranı</h3>
        <br>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    {!!Form::model($duyurular, ['route' => ['duyurular.update', $duyurular->id], "method" =>  "put","files" => true])!!}
                    {!! Form::bsText("duyuru_basligi","Duyuru Başlığı",null,[]) !!}
                    {!! Form::bsTextArea("duyuru_icerigi","Duyuru İçeriği",null,["class" => "form-control",'rows'=>'5','cols'=>'20']) !!}
                    {!! Form::bsSubmit("Güncelle") !!}
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection
@section("js")
@endsection
@section("css")
@endsection

resources/views/admin/kargo_yonetim.blade.php
@extends('layouts.main')
@section('content')
    <div class="container" style="padding: 30px;margin-top: 130px">
        <a class="mx-3" style="color: black " href="{{route('home')}}">Anasayfa</a> > <a class="mx-3" style="color: gray" title="Geri" onclick="window.history.back()">Geri Git</a>  <h4 class="text-center" style="font-family: 'Harlow Solid Italic'">KARGO YÖNETİM EDİT </h4>
        <div class="row" style="margin-bottom: 30px;">

        </div>
        <div class="row">
            <a href="{{route('kargoyonetim.create')}}" class="btn btn-danger mb-5 mx-3">
                <i class="fa fa-plus"></i>
                Yeni Kargo Ekle
            </a>
            <div class="col-md-12">

                <div class="table-responsive">
                    <table class="table table-hover">
                        <thead>
                        <tr>
                            <th>Firma Adı</th>
                            <th>Sabit Fiyat</th>
                            <th>Kargo Durumu</th>
                            <th>Kayıt Tarihi</th>
                            <th class="text-center" >Düzenle</th>
                            <th>Silme</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($kargoYonetim as $b)
                            <tr>
                                <td>{{$b->kargo_adi}}</td>
                                <td>{{$b->kargo_fiyati}}</td>
                                <td>{{$b->kargo_durumu}}</td>
                                <td>{{$b->created_at}}</td>
                                <td class="text-center">
                                    <a href="{{route('kargoyonetim.edit',$b->id)}}" class="btn btn-primary "><i class="fa fa-edit"></i></a>
                                </td>
                                <td> <a href="{{route('ksil',$b->id)}}" class="btn btn-danger" data-method="delete"
                                        data-confirm="Emin Misiniz?"><i class="fa fa-trash"></i></a></td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('js')
    <script src="{{asset("js/laravel-delete.js")}}"></script>
@endsection

resources/views/admin/kariyerraporu.blade.php
@extends('layouts.main')
@section("content")
    <div class="container-fluid"style="margin-top: 150px">
        <a class="mx-3" style="color: black " href="{{route('kontrolmenu')}}">Kontrolmenu</a> > <a class="mx-3" style="color: gray" title="Geri" onclick="window.history.back()">Geri Git</a>
        <div id="chartContainer" style="height: 370px; width: 100%;"></div>
        <?php

        use App\Kariyer;
        use App\User;
        $kariyerler = Kariyer::where('id','<=',16)->get();
        $musteri1 = User::where('kariyer_id',1)->count();
        $musteri2 = User::where('kariyer_id',2)->count();
        $musteri3 = User::where('kariyer_id',3)->count();
        $musteri4 = User::where('kariyer_id',4)->count();
        $musteri5 = User::where('kariyer_id',5)->count();
        $musteri6 = User::where('kariyer_id',6)->count();
        $musteri7 = User::where('kariyer_id',7)->count();
        $musteri8 = User::where('kariyer_id',8)->count();
        $musteri9 = User::where('kariyer_id',9)->count();
        $musteri10 = User::where('kariyer_id',10)->count();
        $musteri11 = User::where('kariyer_id',11)->count();
        $musteri12 = User::where('kariyer_id',12)->count();
        $musteri13 = User::where('kariyer_id',13)->count();
        $musteri14 = User::where('kariyer_id',14)->count();
        $musteri15 = User::where('kariyer_id',15)->count();
        $dataPoints = array(
	array("y" => $musteri1, "label" => $kariyerler[0]->kariyername ),
	array("y" => $musteri2, "label" => $kariyerler[1]->kariyername ),
	array("y" => $musteri3, "label" => $kariyerler[2]->kariyername ),
	array("y" => $musteri4, "label" => $kariyerler[3]->kariyername ),
	array("y" => $musteri5, "label" => $kariyerler[4]->kariyername ),
	array("y" => $musteri6, "label" => $kariyerler[5]->kariyername ),
	array("y" => $musteri7, "label" => $kariyerler[6]->kariyername ),
	array("y" => $musteri8, "label" => $kariyerler[7]->kariyername ),
	array("y" => $musteri9, "label" => $kariyerler[8]->kariyername ),
	array("y" => $musteri10, "label" => $kariyerler[9]->kariyername ),
	array("y" => $musteri11, "label" => $kariyerler[10]->kariyername ),
	array("y" => $musteri12, "label" => $kariyerler[11]->kariyername ),
	array("y" => $musteri13, "label" => $kariyerler[12]->kariyername ),
	array("y" => $musteri14, "label" => $kariyerler[13]->kariyername ),
	array("y" => $musteri15, "label" => $kariyerler[14]->kariyername ),

        );
        ?>
    </div>
@endsection

@section("js")
    <script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>
    <script>
        window.onload = function() {

            var chart = new CanvasJS.Chart("chartContainer", {
                animationEnabled: true,
                theme: "light2",
                title:{
                    text: "Mevcut Kariyer Raporu"
                },
                axisY: {
                    title: "Toplam Kişi Sayıları"
                },
                data: [{
                    type: "column",
                    yValueFormatString: "#,##0.## Kişi",
                    dataPoints: <?php echo json_encode($dataPoints, JSON_NUMERIC_CHECK); ?>
                }]
            });
            chart.render();

        }
    </script>
@endsection

@section("css")
    <style>
        #timeToRender {
            position:absolute;
            top: 10px;
            font-size: 20px;
            font-weight: bold;
            background-color: #d85757;
            padding: 0px 4px;
            color: #ffffff;
        }
    </style>
@endsection

resources/views/admin/lider-cikarma-create.blade.php
@extends('layouts.main')
@section("content")
    <div class="container " style="padding: 30px;margin-top: 130px">
        <a class="mx-3" style="color: black " href="{{route('home')}}">Anasayfa</a> > <a class="mx-3" style="color: gray" title="Geri" onclick="window.history.back()">Geri Git</a> <h3 class="text-center" style="font-family: 'Harlow Solid Italic'">LİDER ÇIKARMA EKRANI</h3>
        <br>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <form method="POST" action="@isset($lider_cikarma){{route('lidercikarma.update',$lider_cikarma->id)}} @endisset" >
                        @csrf
                        @isset($lider_cikarma)
                            @method('put')
                        @endisset
                        <div class="form-group">
                            <label class="mx-2">Kariyer Tutar :</label>
                            <input class="w-25 text-uppercase form-control{{ $errors->has('tutar') ? ' is-invalid' : '' }}" name="tutar" type="text" value="@isset($lider_cikarma) {{$lider_cikarma->tutar}}@endisset">
                        </div>
                        <div class="form-group">
                            <button class="btn btn-success mx-2" type="submit">Kaydet</button>
                            <a class="btn btn-danger" href="{{route('lidercikarma.index')}}">Geri</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

@section("js")
    <script>
        $(document).ready(function() {
            $(".number").keydown(function (e) {
                //  backspace, delete, tab, escape, enter and vb tuşlara izin vermek için.
                if ($.inArray(e.keyCode, [46, 8, 9, 27, 13, 110, 190]) !== -1 ||
                    //  Ctrl+A Tuş kobinasyonuna izin vermek için.
                    (e.keyCode == 65 && e.ctrlKey === true) ||
                    //  Ctrl+C Tuş kobinasyonuna izin vermek için.
                    (e.keyCode == 67 && e.ctrlKey === true) ||
                    //  Ctrl+X Tuş kobinasyonuna izin vermek için.
                    (e.keyCode == 88 && e.ctrlKey === true) ||
                    // home, end, left, right gibi tuşlara izin vermek için.
                    (e.keyCode >= 35 && e.keyCode <= 39)) {

                    return;
                }
                // Basılan Tuş takımının Sayısal bir değer taşıdığından emin olmak için.
                if ((e.shiftKey || (e.keyCode < 48 || e.keyCode > 57)) && (e.keyCode < 96 || e.keyCode > 105)) {
                    e.preventDefault();
                }
            });
        });
    </script>
@endsection

@section("css")
@endsection