routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/oturum/pmenu', 'HomeController@oturum')->name('pmenu')->middleware('auth','onyedi');
    Route::get('/oturum/hesabim', 'HomeController@hesap')->name('hesap')->middleware('auth','onyedi');
Route::get('/anasayfa/hakkimizda', 'HomeController@hk')->name('hk');
Route::get('/anasayfa/kariyerler', 'HomeController@kariyerler')->name('kariyerler');
Route::get('/veosnet/etkinlikler', 'HomeController@etkinlikler')->name('etkinlikler');
Route::get('/veosnet/misyonumuz ve vizyonumuz', 'HomeController@misyon')->name('misyon');
Route::get('/veosnet/iade şartları', 'HomeController@iade')->name('iade');
Route::get('/', 'HomeController@index')->name('home');
Route::get('/contact', 'HomeController@contact')->name('contact');
Route::get('/category/{slug}', 'HomeController@category')->name('category');
Route::get('/product/{slug}', 'HomeController@product')->name('product');
Route::get('/Kurumsal/Bayi Sozlesmesi ve Prosedurler', 'HomeController@bayi')->name('bayi');
Route::get('/Kurumsal/Temsilcilik Sozlesmesi', 'HomeController@temsilcilik')->name('temsilcilik');
Route::get('/Kurumsal/Gizlilik Sozlesmesi','HomeController@gizlilik')->name('gizlilik');
Route::get('/Kurumsal/Dogrudan Satis Sozlesmesi', 'HomeController@dogrudansatis')->name('dogrudansatis');
Route::get('/Kurumsal/Mesafeli Satis Sozlesmesi', 'HomeController@mesafelisatis')->name('mesafelisatis');
Route::get('/Veosnet/İş Modeli', 'HomeController@ismodeli')->name('ismodeli');
Route::get('/Veosnet/Yeni Urunler', 'HomeController@yeniurunler')->name('yeniurunler');
Route::resource('profil-create','ProfilCreateController');
Route::get('dest/{id}','ProfilCreateController@destroy')->name('psil');
Route::get('/Veosnet/Neden Veosnetwork', 'HomeController@nedenveos')->name('nedenveos');
Route::get('/Veosnet/ProfesyonelPazarlama', 'HomeController@ppazarlama')->name('ppazarlama');
Route::get('/PrimMenu/ekip/', 'PrimController@index')->name('ekipagaci')->middleware('auth','onyedi');
Route::get('/VeosNet/cuzdan', 'PrimController@create')->name('cuzdan')->middleware('auth','onyedi');
Route::get('/VeosNet/binary', 'PrimController@binary')->name('binary')->middleware('auth','onyedi');
Route::get('/VeosNet/binary/datatable', 'PrimController@binary_datatable')->name('binary-datatable')->middleware('auth','onyedi');
Route::get('/VeosNet/kazanc', 'PrimController@store')->name('kazanc')->middleware('auth','onyedi');
Route::get('/PrimMenu/{kid}/kazanc', 'PrimController@gonderme')->name('kid')->middleware('auth','onyedi');
Route::get('/view/Kargo', 'HomeController@kargo')->name('kargo');
Route::get('/view/Odemeplanı', 'HomeController@odemeplanı')->name('odemeplanı');
Route::get('/view/basari', 'HomeController@basari')->name('basari');
Route::get('/view/profesyonel_pazarlama', 'HomeController@profesyonelpazarlama')->name('profesyonelpazarlama');
Route::get('/view/genelbakis', 'PrimController@genelbakis')->name('genelbakis')->middleware('auth','onyedi');
Route::get("/view/menu","PrimController@menu")->name('menu')->middleware('auth','onyedi');
Route::get('/view/guvenliodeme','HomeController@cartman')->name('cartman')->middleware('auth','onyedi');
Route::get('/view/TarimOnaylidir','HomeController@tarimbelge')->name('tarimbelge');
Route::get('/view/Kazancozeti','HomeController@kazancozeti')->name('kazancozeti')->middleware('auth','onyedi');
Route::get('/VeosNet/Kazancozeti/datatable','GelirController@kazancozeti_datatable')->name('kazancozeti.datatable')->middleware('auth','onyedi');
Route::get('/VeosNet/gelenpv/datatable','GelenpvController@gelenpv_datatable')->name('gelenpv.datatable')->middleware('auth','onyedi');
Route::get('Veosnet/Pv/Cv Gelirlerim','GelenpvController@index')->name('gelenpvsyf');
Route::get('/VeosNet/gelirlerim','HomeController@gelirlerim')->name('gelirlerim')->middleware('auth','onyedi');
Route::get('VeosNet/S.S.S','HomeController@sss')->name('sss');
Route::resource('mailorder','MailOrderController');
Route::get('Kampanyalar','HomeController@kampanyalar')->name('kampanyalar');
Route::get('haberlerimiz','HomeController@haber2')->name('haberler2');
Route::get('Bilgilendirme','HomeController@bilgilendirme')->name('bilgilendirme21')->middleware('auth','onyedi');
Route::get('hesapbilgileri','HomeController@banka')->name('banka')->middleware('auth','onyedi');
Route::get('VeosNet/Sozlesmeler','HomeController@sozlesmemusteri')->name('sozlesmemusteri');
Route::get('VeosNet/sozlesmelerimiz/{uuid}/download','HomeController@download')->name('sozlesme.download')->middleware('auth');
Route::get('VeosNet/kullaniciilcirosu','HomeController@il_ciro')->name('il_ciro')->middleware('auth','onyedi');
Route::get('VeosNet/kullanicitrciro','HomeController@tr_ciro')->name('tr_ciro')->middleware('auth','onyedi');
Route::get('VeosNet/kullanicidunyaciro','HomeController@dunya_ciro')->name('dunya_ciro')->middleware('auth','onyedi');
Route::get('VeosNet/kullaniciarabaciro','HomeController@araba_ciro')->name('araba_ciro')->middleware('auth','onyedi');
Route::get('VeosNet/kullanicibolgeciro','HomeController@bolge_ciro')->name('bolge_ciro')->middleware('auth','onyedi');
Route::get('veosnet/GuvenliOdeme','HomeController@mailorder')->name('mailorder');
Route::resource('VeosNet/odemetalebi','OdemeTalebiController')->middleware('auth','onyedi');
Route::resource('message','MessageController');
Route::get('/Veosnet/Kataloglar','HomeController@kullanici_katalog')->name('kullanici_katalog');

Route::group(['namespace'=>"Admin"],function (){
    Route::get('/VeosNet/kullanici/katalog/{uuid}/download', 'KatalogController@download')->name('katalog.download');
});
Route::get('VeosNet/EftDurum','HomeController@musteri_eft_durum')->name('musteri_eft_durum')->middleware('auth','onyedi');

Route::get('veosnet/alt-uyelik-ekle','PrimController@farkli_il_kayit_index')->middleware('auth')->name('yeni-alt-bayi');
Route::post('veosnet/alt-uyelik-ekle','PrimController@farkli_il_kayit_store')->middleware('auth')->name('yeni-alt-bayi.store');
Route::get('veosnet/alt-uyeliklerim','PrimController@alt_bayiliklerim')->middleware('auth')->name('alt-bayiliklerim');

Route::get('logout','Auth\LoginController@logout');
    //Route::get('kayit/{konum}','uyelikController@index')->name('kayityapma');
Route::get('kayit/{konum}/{sps}','uyelikController@index')->name('kayityapma')->middleware('auth');
Route::post('kayit','uyelikController@store')->name('kayityapma.kayıt')->middleware('auth');
Route::get('KonumBilgilendirme','PrimController@bilgilendirme')->name('bilgilendirme')->middleware('auth');
Route::get('isteklerim','PrimController@isteklerim')->name('isteklerim')->middleware('auth');
Route::get('ekiptakip','PrimController@ekiptakip')->name('ekiptakip')->middleware('auth');
Route::get('ekiplistesi','PrimController@ekiplistesi')->name('ekiplistesi')->middleware('auth');
Route::get('change-password', 'ChangePasswordController@index')->name('change')->middleware('auth');
Route::post('change-password', 'ChangePasswordController@store')->name('change.password')->middleware('auth');
Route::post('konumlandirin/{ikid}','Admin\TransferController@iskonum')->name('iskonum')->middleware('auth');

Route::post('odeme-cuzdan/{tutar}','GelirController@cuzdanOdeme')->name('cuzdan.odeme')->middleware('auth');
Route::get('bankahesapbilgileri','PrimController@bankahesapbilgileri')->name('bankahesapbilgileri')->middleware('auth');
Route::get('bankahesapbilgileri/{order_no}','PrimController@bankahesapbilgilerikisiyeozel')->name('bankahesapbilgileri.kisiyeozel')->middleware('auth');


Route::group(["middleware" => ["is_thisAdmin","auth"]],function (){
    Route::group(["namespace" => "Admin"], function (){
        Route::resource("admin-users","UsersController");
        Route::get("admin-users/datatable/d","UsersController@users_datatable")->name('admin-users.datatable');
        Route::get("admin-users/datatable/active","UsersController@users_active_datatable")->name('admin-users.active.datatable');
        Route::get("admin-users/datatable/pasive","UsersController@users_passive_datatable")->name('admin-users.passive.datatable');
        Route::resource("admin-category","CategoryController");
        Route::resource("admin-products","ProductController");
        Route::resource("admin-orders","OrderController");
        Route::resource('kariyer','KariyerController');
        Route::resource('transfer','TransferController');
        Route::get('Binarykontrol','TransferController@adminagac')->name('binarykontrol');
        Route::post('admin/admin-pv/{id}/ekle','TransferController@admin_pv_ekleme')->name('admin.pv.ekle');
        Route::post('admin/admin-cv/{id}/ekle','TransferController@admin_cv_ekleme')->name('admin.cv.ekle');
        Route::get('AdminEkiplistesi','TransferController@adminekip')->name('adminekip');
        Route::get('transfer/{id}/sil','TransferController@destroy2')->name('transfersilme');
        Route::post('transfer/{tid}','TransferController@transferet')->name('transfer');
        Route::post('konumlandir/{kdid}','TransferController@konumlandir')->name('konumlandir');
        Route::get('kontrolmenu','TransferController@kontrolmenu')->name('kontrolmenu');
        Route::get('aktif_pasif','TransferController@aktif')->name('aktif');
        Route::get('users-pasif','TransferController@pasif')->name('users.passive');
        Route::get('aracciro','TransferController@araciro')->name('adminaraciro');
        Route::get('tazminat','TransferController@tazminat')->name('tazminat');
        Route::get('tazminat/{id}','TransferController@tazminatode')->name('tazminat-ode');

resources/views/layouts/MailOrder.blade.php
@extends('layouts.main')
@section('content')
    @php $urunler=App\BasketProduct::where('basket_id',session('active_basket_id'))->with('product')->get(); @endphp
    <p style="margin-top: 160px" class="alert alert-info">veosnet.com firması tarafından sizin için
        @foreach($urunler as $urunler)
            @if($urunler->product-> turu == 'urun')
                <p class="text-dark"> {{$tutar}} </p>
            @else
                <p class="text-dark">
                    {{Cart::subtotal()}}
                </p>
            @endif @endforeach
       ₺ tutarında bir ödeme isteği oluşturuldu. Ödemeyi gerçekleştirebilmek için kart bilgilerinizi girip Ödeme Yap butonuna tıklamanız gerekmektedir.</p>
    <div id="root">
        <div class="mx-5" id="card">
            <div id="card-bottom"></div>
            <div id="card-top">
                <div class="logo">
                    <svg version="1.1" id="visa" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="72px" height="72px" viewBox="0 0 47.834 47.834" style="enable-background:new 0 0 47.834 47.834;" fill="white">
                        <g>
                            <g>
                                <path d="M44.688,16.814h-3.004c-0.933,0-1.627,0.254-2.037,1.184l-5.773,13.074h4.083c0,0,0.666-1.758,0.817-2.143
                     c0.447,0,4.414,0.006,4.979,0.006c0.116,0.498,0.474,2.137,0.474,2.137h3.607L44.688,16.814z M39.893,26.01
                     c0.32-0.819,1.549-3.987,1.549-3.987c-0.021,0.039,0.317-0.825,0.518-1.362l0.262,1.23c0,0,0.745,3.406,0.901,4.119H39.893z
                     M34.146,26.404c-0.028,2.963-2.684,4.875-6.771,4.875c-1.743-0.018-3.422-0.361-4.332-0.76l0.547-3.193l0.501,0.228
                     c1.277,0.532,2.104,0.747,3.661,0.747c1.117,0,2.313-0.438,2.325-1.393c0.007-0.625-0.501-1.07-2.016-1.77
                     c-1.476-0.683-3.43-1.827-3.405-3.876c0.021-2.773,2.729-4.708,6.571-4.708c1.506,0,2.713,0.31,3.483,0.599l-0.526,3.092
                     l-0.351-0.165c-0.716-0.288-1.638-0.566-2.91-0.546c-1.522,0-2.228,0.634-2.228,1.227c-0.008,0.668,0.824,1.108,2.184,1.77
                     C33.126,23.546,34.163,24.783,34.146,26.404z M0,16.962l0.05-0.286h6.028c0.813,0.031,1.468,0.29,1.694,1.159l1.311,6.304
                     C7.795,20.842,4.691,18.099,0,16.962z M17.581,16.812l-6.123,14.239l-4.114,0.007L3.862,19.161
                     c2.503,1.602,4.635,4.144,5.386,5.914l0.406,1.469l3.808-9.729L17.581,16.812L17.581,16.812z M19.153,16.8h3.89L20.61,31.066
                     h-3.888L19.153,16.8z"/>
                            </g>
                        </g>
                    </svg>
                </div>
                <div class="card-number">
                    XXXX XXXX XXXX XXXX
                </div>
                <div class="row-container">
                    <div class="card-holder">
                        <span>Kart Sahibi</span>
                        <span></span>
                    </div>
                    <div class="expiry">
                        <span>Son Kullanım Tarihi</span>
                        <span>
            <span class="expiry-month">00</span>
            /
            <span class="expiry-year">00</span>
          </span>
                    </div>
                    <div class="cvc">
                        <span>CVC</span>
                        <span>___</span>
                    </div>
                </div>
            </div>
        </div>
        <div class="form-group mx-2 ">
        <form method="POST" action="{{route('mailorder.update', $mailorder->id)}}" id="form" >
            @csrf
            @isset($mailorder)
                @method('put')
            @endisset
               <header>
                   <h2 style="font-family: 'Harlow Solid Italic'">ÖDEME BİLGİSİ</h2>
               </header>
               <div class="">
                   <p>Kart Numarası</p>
                   <span>
                    <input class="form-control {{ $errors->has('cardname') ? ' is-invalid' : '' }}" name="cardnu"  maxlength="19" value="@isset($mailorder){{$mailorder->cardnu}}@else {{old('cardnu')}} @endisset" onkeypress='return event.keyCode >= 48 && event.keyCode <= 57' placeholder="1234 5678 9123 4567"/>
                </span>
               </div>
               <div class="card-holder">
                   <p>Kart Sahibi</p>
                   <input class="form-control {{ $errors->has('cardname') ? ' is-invalid' : '' }}" value="@isset($mailorder){{$mailorder->cardname}}@else {{old('cardname')}} @endisset"  name="cardname" type="text" placeholder="Veos Network"/>
               </div>
               <div class="row-container">
                   <div class="">
                       <p>Ay</p>
                       <select class="form-control {{ $errors->has('cardmonth') ? ' is-invalid' : '' }}" value="@isset($mailorder){{$mailorder->cardmonth}}@else {{old('cardmonth')}} @endisset"  name="cardmonth">
                           <option></option>
                           <option value="01">01</option>
                           <option value="02">02</option>
                           <option value="03">03</option>
                           <option value="04">04</option>
                           <option value="05">05</option>
                           <option value="06">06</option>
                           <option value="07">07</option>
                           <option value="08">08</option>
                           <option value="09">09</option>
                           <option value="10">10</option>
                           <option value="11">11</option>
                           <option value="12">12</option>
                       </select>
                   </div>
                   <div class="">
                       <p class="">Yıl</p>
                       <select class="form-control {{ $errors->has('cardyear') ? ' is-invalid' : '' }}"value="@isset($mailorder){{$mailorder->cardyear}}@else {{old('cardyear')}} @endisset"  name="cardyear">
                           <option></option>
                           <option value="20">2020</option>
                           <option value="21">2021</option>
                           <option value="22">2022</option>
                           <option value="23">2023</option>
                           <option value="24">2024</option>
                           <option value="25">2025</option>
                           <option value="26">2026</option>
                           <option value="27">2027</option>
                           <option value="28">2028</option>
                           <option value="29">2029</option>
                           <option value="30">2030</option>
                       </select>
                   </div>
                   <div class="">
                       <p>Cvc</p>
                       <input width="25" class="form-control {{ $errors->has('cardcvc') ? ' is-invalid' : '' }}" value="@isset($mailorder){{$mailorder->cardcvc}}@else {{old('cardcvc')}} @endisset"  name="cardcvc" type="text" maxlength="3" onkeypress='return event.keyCode >= 48 && event.keyCode <= 57'/>
                   </div>
               </div>
                   <button class="mt-3" type="submit">Ödeme Yap</button>
        </form>
        </div>
    </div>

@endsection
@section('js')
    <script>
        $(document).ready(function() {
            $(".number").keydown(function (e) {
                //  backspace, delete, tab, escape, enter and vb tuşlara izin vermek için.
                if ($.inArray(e.keyCode, [46, 8, 9, 27, 13, 110, 190]) !== -1 ||
                    //  Ctrl+A Tuş kobinasyonuna izin vermek için.
                    (e.keyCode == 65 && e.ctrlKey === true) ||
                    //  Ctrl+C Tuş kobinasyonuna izin vermek için.
                    (e.keyCode == 67 && e.ctrlKey === true) ||
                    //  Ctrl+X Tuş kobinasyonuna izin vermek için.
                    (e.keyCode == 88 && e.ctrlKey === true) ||
                    // home, end, left, right gibi tuşlara izin vermek için.
                    (e.keyCode >= 35 && e.keyCode <= 39)) {

                    return;
                }
                // Basılan Tuş takımının Sayısal bir değer taşıdığından emin olmak için.
                if ((e.shiftKey || (e.keyCode < 48 || e.keyCode > 57)) && (e.keyCode < 96 || e.keyCode > 105)) {
                    e.preventDefault();
                }
            });
        });
    </script>

@section('css')
    <link rel="stylesheet" href="{{asset('css/mailorder.css')}}">
@endsection

resources/views/layouts/alt-bayiklerim.blade.php
@extends('layouts.main')
@section("content")
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <link rel="stylesheet" href="{{asset('css/menu.css')}}">
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>

    <div class=""style="margin-top: 100px;background-image: url('https://cutewallpaper.org/21/white-hd-wallpaper/Abstract-Wallpaper-White.jpg')" >
        <div class="col-md-12 mb-2 ">
            <div class="row">
                <div class="col-md-6 mt-3 ">
                    <p style="color: black"><i class="fa fa-user mx-3 "></i>Sayın;&nbsp; {{auth()->user()->name}} {{auth()->user()->surname}}</p>
                    <p style="color: black"><i class="fa fa-user-secret mx-3"></i>Kullanıcı Numaranız: [ {{auth()->user()->id}} ]</p>
                </div>
                <div class="col-md-6 mt-3">
                    <p class=" mt-2 mx-5"style="color: black"><i class="fa fa-briefcase mx-3"></i> Kariyeriniz :&nbsp; {{auth()->user()->kariyer->kariyername}}</p>
                    <p class="mx-5"  style="color: black"> <i class="fa fa-battery-quarter mx-3"></i>Şuan ki Kariyer Puanınız :&nbsp; {{auth()->user()->ara_pv}} PV</p>
                </div>
            </div>
            <div style="height: 1px;background-image: url('https://wallpaperaccess.com/full/1216046.jpg')"></div>
        </div>
        <div class="row">
            <div class="col-md-12 ">
                @if(auth()->user()->id== 10001)
                @else
                    <div class="col-md-3">
                        <ul id="menu-v">
                            <li>  <h5 class="text-center text-white"  >BÖLGE ALT BAYİLİKLERİM</h5></li>
                            <li><a class=""title="Geri" onclick="window.history.back()">Geri Gitmek İstiyorum</a></li>
                            <li>
                                <a class="arrow" href="#">Genel Bakış</a>
                                <ul>
                                    <li>
                                        <a class="arrow" href="{{route('alt-bayiliklerim')}}">
                                            İllerdeki Bayiliklerim
                                        </a>
                                    </li>
                                    <li>
                                        <a  class="arrow" href="{{route('yeni-alt-bayi')}}">
                                            Yeni İlde Bayi Aç
                                        </a>
                                    </li>
                                </ul>
                            </li>
                            <li>
                                <a class="" href= "{{route("kazanc")}}"> Ekibim</a>
                            <li><a class="" href="{{route('binary')}}"> Soy Ağacı Kazancım</a></li>
                            <li>  <a class="" href="{{route("cuzdan")}}"> Cüzdanım</a></li>
                            <li><a class="" href="{{route("isteklerim")}}"> İsteklerim</a></li>
                            <li><a class="" href="{{route("kazancozeti")}}">Gelirlerim</a> </li>
                            <li> <a class="" href="{{route("gelenpvsyf")}}"> Pv/Cv Gelirlerim</a></li>
                            <li><a class="" href="{{route("hesap")}}">Hesap Menü</a></li>
                        </ul>
                    </div>
                @endif
                <div class="row">
                    <div class="col-md-12">
                        <div class="table-responsive">
                            <table class="table table-bordered table-hover">
                                <tr>
                                    <th>Kullanıcı Numarası</th>
                                    <th>Bölge</th>
                                    <th>İller</th>
                                    <th class="text-center">Kayıt Tarih</th>
                                </tr>
                                @foreach($users as $user)
                                    <tr>
                                        <td>{{$user->id}}</td>
                                        <td>{{$user->bolge->name}}</td>
                                        <td>{{$user->iller->name}}</td>
                                        <td>{{$user->created_at}}</td>
                                    </tr>
                                @endforeach
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section("customJs")
@endsection
@section("customCss")
@endsection

resources/views/layouts/cartman2.blade.php
@extends('layouts.main')
@section("content")
    <div class="container" style="margin-top: 160px">
        <div class="row">
            <div class="col-md-12">
                <h4 class="mb-5 mt-5 mx-5" style="font-family: 'Harlow Solid Italic'"> VEOSNET HESAP BİLGİLERİ</h4>
                <div class="row">
                    <div class="col-md-6">
                        <div class="table-responsive">
                            <table class="table table-hover">
                                <thead>
                                <tr>
                                    <th>Hesap Sahibi</th>
                                    <th>İban Nu:</th>
                                    <th>Hesap Nu:</th>
                                    <th>Banka Adı</th>
                                    <th>Şube Kodu</th>
                                    <th>Şube Adı</th>
                                    <th>Kayıt Tarihi</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($banka as $b)
                                    <tr>
                                        <td>{{$b->hesap_sahibi}}</td>
                                        <td>{{$b->iban_no}}</td>
                                        <td>{{$b->hesap_no}}</td>
                                        <td>{{$b->banka_adi}}</td>
                                        <td>{{$b->sube_kodu}}</td>
                                        <td>{{$b->sube_adi}}</td>
                                        <td>{{$b->created_at}}</td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="col-md-6 col-sm-12">
                        <div class="row">
                            <h5 class="mb-5 mx-3 " style="color: slategray"><i style="color: black">Sayın;</i> {{$kisi->name}} {{$kisi->surname}}</h5>
                            <div class="col-md-12">
                                <h4 class="mb-5 text-center "><p class="text-success">[ Ödenecek Tutarınız ]</p> {{$price}} ₺</h4>
                            <p>
                              VeosNet Eft Hesap Bilgileri Yan Tarafta Yer Almaktadır.
                            </p>
                             <p>
                                 Eft Yaptıktan Sonra Talebiniz Listemize Düşecektir.
                             </p>
                                <marquee  behavior="" direction="">  <strong class="mt-3"> VeosNet'i Tercih Ettiğiniz İçin Teşekkür Eder, Sağlıklı Günler Dileriz... </strong></marquee>
                            </div>
                        </div>
                        <img src="{{asset('assets/new images/kartlar.jpg')}}" alt="">
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section("js")
    <script>
        $(document).ready(function() {
            $(".number").keydown(function (e) {
                //  backspace, delete, tab, escape, enter and vb tuşlara izin vermek için.
                if ($.inArray(e.keyCode, [46, 8, 9, 27, 13, 110, 190]) !== -1 ||
                    //  Ctrl+A Tuş kobinasyonuna izin vermek için.
                    (e.keyCode == 65 && e.ctrlKey === true) ||
                    //  Ctrl+C Tuş kobinasyonuna izin vermek için.
                    (e.keyCode == 67 && e.ctrlKey === true) ||
                    //  Ctrl+X Tuş kobinasyonuna izin vermek için.
                    (e.keyCode == 88 && e.ctrlKey === true) ||
                    // home, end, left, right gibi tuşlara izin vermek için.
                    (e.keyCode >= 35 && e.keyCode <= 39)) {

                    return;
                }
                // Basılan Tuş takımının Sayısal bir değer taşıdığından emin olmak için.
                if ((e.shiftKey || (e.keyCode < 48 || e.keyCode > 57)) && (e.keyCode < 96 || e.keyCode > 105)) {
                    e.preventDefault();
                }
            });
        });
    </script>
@endsection
@section("css")
@endsection

resources/views/layouts/gizlilik.blade.php
@extends("layouts.main")
@section("content")
    <div class="container" style="margin-top: 170px">
        <object data="{{asset("uploads/newgizlilikpolitikası.pdf")}}" type="application/pdf" width="100%" height="600px">
            <p>Alternative text - include a link <a href="https://metaldolap.com.tr/uploads/site/katalog.pdf">to the PDF!</a></p>
        </object>
    </div>

@endsection
@section("customJs")
@endsection

@section("customCss")
@endsection

resources/views/layouts/iade.blade.php
@extends("layouts.main")
@section("content")
    <div class="container" style="margin-top: 170px">
        <object data="{{asset("uploads/newiadevecayma.pdf")}}" type="application/pdf" width="100%" height="600px">
            <p>Alternative text - include a link <a href="https://metaldolap.com.tr/uploads/site/katalog.pdf">to the PDF!</a></p>
        </object>
    </div>
@endsection

@section("customJs")
@endsection

@section("customCss")
@endsection